### ISSUE TITLE
could not install the app on the device read the error above for details.

### ISSUE THREAD

**Issue by matisha001** [lipeiwei-szu/ReactNativeOne#10]
react-native环境是配置好的，可以新建项目并运行，安卓环境ok，有安装android studio2.2，模拟器和真机运行都ok。
这个项目下载后，npm install正常，在react-native run-android的时候，出现题目所示的错误。完整错误信息如下：
could not install the app on the device read the error above for details.
meke sure you have an Android emulator running or a device connected and have set up your Android development envirenment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by lipeiwei-szu** [comment]
加我qq544063528，我看看能不能帮忙解答@matisha001

**Comment by lipeiwei-szu** [comment]
@matisha001  你好，我提交了代码，升级了RN版本，你pull一下代码，然后重新npm install，应该就可以运行了，有问题加QQ群436338753
