### ISSUE TITLE
关于IOS真机图片显示的问题

### ISSUE THREAD

**Issue by tiger8888** [lipeiwei-szu/ReactNativeOne#12]
问题描述:
app 首页的内容滚动,当图片都加载完了之后,我滚动到最后一页,然后再滚动到第一页,这时第一页的图片就显示不出来了,要等个十来秒,才显示出来....

我试过iphone5s,iphone6p都有这个问题,在安卓手机倒没有这个问题

**Comment by lipeiwei-szu** [comment]
@tiger8888  后来在qq上我跟你说了之后你找到问题了吗
