### ISSUE TITLE
关于电影详情页

### ISSUE THREAD

**Issue by yogu2017** [lipeiwei-szu/ReactNativeOne#14]
我发现你的也是这样子，详情页里面的内容也没有图片，官方的是有图片的，不知道你有没有解决办法？还有你的内容里有HTML格式~~~

**Comment by lipeiwei-szu** [comment]
@yogu2017 我记得官方应该是没图片的吧？其实在阅读模块中，文章也都是有html标签的，但因为如果用WebView的话，需要解决ListView嵌套WebView的问题，所以我是选择使用正则表达式将html标签去掉，你可以参考一下代码。电影详情页的去除html标签我就还没做，这段时间会做的，顺便解决一下相关bug，优化一下性能问题

**Comment by lipeiwei-szu** [comment]
@yogu2017 可加qq群436338753讨论

**Comment by yogu2017** [comment]
我发现了，版本变化，get的时候加上版本号即可—version=v4.1
