### ISSUE TITLE
为什么你的项目的node_module中没有/Libraries/Core ??????，找了我好久啊，还没解决

### ISSUE THREAD

**Issue by 1242128273wangpeng** [lipeiwei-szu/ReactNativeOne#16]
发生这个错误：SyntaxError:Strict mode does not allow function declaration in a lexically nested statement.

![qq 20170318113640](https://cloud.githubusercontent.com/assets/10842360/24068664/b41f98ac-0bcf-11e7-8aaf-37e04afe3e46.png)

**Comment by lipeiwei-szu** [comment]
@1242128273wangpeng  这段代码是在另外一个位置，我按照提示改了，但是也没有用。所以我将RN版本升级到0.39，你可以pull一下代码，然后重新npm install , 就可以运行了。可以加qq群436338753
