### ISSUE TITLE
我在ios模拟器中运行报错，知道什么原因吗，谢谢

### ISSUE THREAD

**Issue by qiushi2012** [lipeiwei-szu/ReactNativeOne#21]
** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze RCTLocationObserver.m

(1 command with analyzer issues)

The following build commands failed:
	CompileC /demo/ReactNativeOne-master/ios/build/Build/Intermediates/RCTSettings.build/Debug-iphonesimulator/RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o RCTSettingsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/ReactNativeOne.app
Launching com.reactnativeone
com.reactnativeone: 1199

**Comment by lipeiwei-szu** [comment]
我提交了代码，你们再拉取，删除node_modules，重新npm install。
