### ISSUE TITLE
我在android模拟器中运行报这个错，知道什么原因吗

### ISSUE THREAD

**Issue by qiushi2012** [lipeiwei-szu/ReactNativeOne#22]
demo/ReactNativeOne-master/android/app/src/main/java/com/reactnativeone/MainApplication.java:19: 错误: <匿名com.reactnativeone.MainApplication$1>中的getUseDeveloperSupport()无法覆盖ReactNativeHost中的getUseDeveloperSupport()
    protected boolean getUseDeveloperSupport() {
                      ^
  正在尝试分配更低的访问权限; 以前为public
1 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by lipeiwei-szu** [comment]
我提交了代码，你们再拉取，删除node_modules，重新npm install。

**Comment by qiushi2012** [comment]
可以运行了，谢谢，但是电影版本没数据啊，能搞点数据吗，谢谢！

**Comment by qiushi2012** [comment]
可以运行了，谢谢，但是电影板块没数据啊，能搞点数据吗，谢谢！

**Comment by lipeiwei-szu** [comment]
@qiushi2012 官方接口数据中cover字段不见了，这我也没办法啊。你可以将电影列表item用本地图片填充一下，这样子就可以点击进入电影详情页了
