### ISSUE TITLE
这个问题怎么回事？

### ISSUE THREAD

**Issue by wangwenxiao5** [lipeiwei-szu/ReactNativeOne#23]
Building and installing the app on the device (cd android && gradlew.bat install
Debug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:12024) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje
ction id: 2): TypeError: Cannot read property 'message' of undefined
(node:12024) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
Android  windows node8.0.0 项目无法在真机运行

**Comment by JasonGaoH** [comment]
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:4504) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

JS server already running.
Running D:\Users\Administrator\AppData\Local\Android\sdk/platform-tools/adb -s f7724343 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:4504) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

这个无法运行时什么问题？

**Comment by koupeng** [comment]
我的也是这个问题？咋解决啊？

**Comment by lipeiwei-szu** [comment]
我提交了代码，你们再拉取，删除node_modules，重新npm install
