### ISSUE TITLE
ios 模拟器运行报错

### ISSUE THREAD

**Issue by ZYHB** [lipeiwei-szu/ReactNativeOne#24]
undefined is not an object (evaluating 'ViewPropTypes.style')

**Comment by wanyunhao** [comment]
同求

**Comment by lipeiwei-szu** [comment]
我提交了代码，你们再拉取，删除node_modules，重新npm install。
很明显，你这个bug是因为react-native-scrollable-tab-view这个库代码有问题@ZYHB
