### ISSUE TITLE
react-native run-android faild in windows

### ISSUE THREAD

**Issue by charleylla** [lipeiwei-szu/ReactNativeOne#26]
在 windows 下运行 run-android 失败：
```
Starting JS server...
Running D:\Android_SDK\/platform-tools/adb -s 192.168.238.101:5555 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat installDebug...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.
```
我克隆项目后进行了以下操作：
```
npm i
react-native run-android
```
出现了这个错误

**Comment by vivianli-me** [comment]
命令行输入 adb devices 确认一下是否能检测到模拟器设备@charleylla

**Comment by charleylla** [comment]
@lipeiwei-szu 可以检测到的，但终端提示似乎不能识别，我怀疑是不是项目中依赖的版本问题，我使用新版本的rn可以构建成功的

**Comment by vivianli-me** [comment]
@charleylla 我大部分第三方库都锁定了版本，应该不会出现依赖上的问题啊，前不久我才测试过一遍，不过是在mac平台下

**Comment by songzhihao** [comment]
我也遇见了同样的问题

**Comment by nianyi778** [comment]
mac 也遇到类似问题

**Comment by nianyi778** [comment]
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.

**Comment by vanceeasleaf** [comment]
win7 相同的问题

**Comment by vivianli-me** [comment]
由于已经过了两三年，ONE的接口很多都改了，所以该应用很多接口都无法正常使用了，抱歉
