### ISSUE TITLE
mac 启动报错 error no such file or directory

### ISSUE THREAD

**Issue by hermitcrabcai** [lipeiwei-szu/ReactNativeOne#28]
![image](https://user-images.githubusercontent.com/26593656/33817119-b392bc76-de78-11e7-9221-d2644a9f217b.png)

**Comment by Circleee** [comment]
我也是这个问题

**Comment by vivianli-me** [comment]
由于已经过了三年了，ONE的接口很多都改了，所以该应用很多接口都无法正常使用了，所以该代码库不再维护了，抱歉 @hermitcrabcai  @Circleee

**Comment by Circleee** [comment]
### 好的
