### ISSUE TITLE
reactpackager 报错无法运行

### ISSUE THREAD

**Issue by HanAsteroid** [lipeiwei-szu/ReactNativeOne#3]
Cannot read property 'on' of undefined

~
Process terminated. Press <enter> to close the window

**Comment by lipeiwei-szu** [comment]
给的信息太少，无法判断是什么问题。你先确保你的react-native开发环境是正常的。

**Comment by erhutime** [comment]
@HanAsteroid 我之前也遇到这样的问题，是通过git下载的源码，后来，也是这样的错误，后来，把代码下载导入，问题就没有了。

**Comment by liulian1993** [comment]
'Orientation.h' file not found , 从git上拉下来的代码  运行很多文件都没有 怎么解决?    刚开始接触RN

**Comment by sjclijie** [comment]
我也遇到相同的问题，npm start 时出现的

**Comment by niunaruto** [comment]
代码下下来报错：Orientation.h文件找不到，把Orientation相关代码注释后又报：
ld: library not found for -lRCTToast
clang: error: linker command failed with exit code 1 (use -v to see invocation)
不知是什么问题

**Comment by lipeiwei-szu** [comment]
@liulian1993 @sjclijie 确保执行了npm install
