### ISSUE TITLE
接口文档的链接打不开

### ISSUE THREAD

**Issue by qfeung** [lipeiwei-szu/ReactNativeOne#30]

**Comment by vivianli-me** [comment]
@qfeung 由于可能涉及到版权的问题，所以之前已经将源链接删除，可以在github多搜搜，当时有些用户fork下来了，比如 https://github.com/zuijiaoluo/ONE-API

**Comment by JasonWu008** [comment]
请问API是停用了还是只是没有公开了？

**Comment by vivianli-me** [comment]
@JasonWu008 因版权问题，接口文档已删除，但可以在github搜索"ONE-API"，可以搜索得到，当时有人fork下来了。由于已经过了很久，ONE的接口很多都改了，所以该应用很多接口都无法正常使用了，抱歉
