### ISSUE TITLE
TypeError:undefined is not an object(evaluating '_configProvider.remoteModuleConfig')

### ISSUE THREAD

**Issue by italks** [lipeiwei-szu/ReactNativeOne#4]
![image](https://cloud.githubusercontent.com/assets/1667764/20256995/cb1308f0-aa81-11e6-9f29-5a54d5b35155.png)

**Comment by italks** [comment]
刚找到能完美运行的rn例子，想要学学呢，居然因侵权删除了，伤心呀

**Comment by lipeiwei-szu** [comment]
@italks 你好，已经恢复
