### ISSUE TITLE
Redux和NavigationExperimental

### ISSUE THREAD

**Issue by RtzX** [lipeiwei-szu/ReactNativeOne#7]
Rt.
学习了一下源码.看到只有播放部分使用的redux .其他的部分还是this.setState 来控制
NavigationExperimental 和Navigator 哪个更好. Navigator是停止维护了吗?
假如有4个tab.那么没有tab 都是拥有一个导航栈的,并且管理的吗?
  新手..谢谢

**Comment by lipeiwei-szu** [comment]
个人觉得，全局性的共享数据用redux来管理，而组件内部独有的状态用this.state来维护即可，没有必要用redux来管理所有的组件状态，那样子会很复杂，因为多了很多的action、reducer，你可以多Google看看redux相关实现思想跟应用思想。至于NavigationExperimental 和Navigator哪个更好，仁者见仁智者见智，Navigator并没有停止维护，你看看官方文档就知道了，记住，是官方英文文档，而不是中文版的翻译文档。最后一个问题看不懂你想问什么
