### ISSUE TITLE
是否考虑RN0.40版本下的兼容？

### ISSUE THREAD

**Issue by xuanskyer** [lipeiwei-szu/ReactNativeOne#8]
不知道是否计划考虑RN0.40+版本下的兼容？

**Comment by lipeiwei-szu** [comment]
@xuanskyer 近期会找时间进行升级的

**Comment by lipeiwei-szu** [comment]
@xuanskyer 今天本来是要升级到RN@0.40.0以上，但是在iOS端一直有个问题解决不了，而且第三方库react-native-orentation没有兼容RN@0.40.0以上，所以我今天暂且将版本升级到0.39.0，已提交了代码。接下来我会跟进这个问题的
