### ISSUE TITLE
could not install the app on the device read the error above for details

### ISSUE THREAD

**Issue by lu-xu** [lipeiwei-szu/ReactNativeOne#9]
react-native环境是配置好的，可以新建项目并运行，安卓环境ok，有安装android studio2.2，模拟器和真机运行都ok。
这个项目下载后，npm install正常，在react-native run-android的时候，出现题目所示的错误。完整错误信息如下：
could not install the app on the device read the error above for details.
meke sure you have an Android emulator running or a device connected and have set up your Android development envirenment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by yangxiaoge** [comment]
我也遇到相同问题!

**Comment by zaoqishibing** [comment]
遇到同样问题，目前还没有解决

**Comment by matisha001** [comment]
react-native环境是配置好的，可以新建项目并运行，安卓环境ok，有安装android studio2.2，模拟器和真机运行都ok。
这个项目下载后，npm install正常，在react-native run-android的时候，出现题目所示的错误。完整错误信息如下：
could not install the app on the device read the error above for details.
meke sure you have an Android emulator running or a device connected and have set up your Android development envirenment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by lipeiwei-szu** [comment]
@a1510312433 @yangxiaoge @zaoqishibing @matisha001 
目前还有问题的加我qq544063528，我看看能不能帮忙解答

**Comment by milayihe** [comment]
我也是遇到奇怪的问题，提示： Requiring unknown module "0"

**Comment by atotoj** [comment]
这个问题解决了吗？

**Comment by lipeiwei-szu** [comment]
@a1510312433 @yangxiaoge @zaoqishibing @matisha001 @milayihe  我提交了代码，升级了RN版本，你pull一下代码，然后重新npm install，应该就可以运行了，有问题加QQ群436338753

**Comment by lingyunzhu** [comment]
同样遇到这个问题，请问大家解决了么？

**Comment by sun2582589** [comment]
我刚下载的也是这样，rn版本的问题吗？我现在安装的是最新的rn版本

**Comment by lipeiwei-szu** [comment]
我提交了代码，修改了package.json中的版本信息，拉取并重新npm install一下。请直接用package.json，暂时先不要去升级到新的RN版本
